In [6]:
import requests

In [7]:
headers= {'User-Agent' : 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36'}

In [8]:
url='https://sg.sbiz.or.kr/godo/stat/upso.sg'

In [9]:
res = requests.get(url, headers = headers,verify=False)
# verify = False를 빼면 오류가 생기는데 그 해결방안을 검색해보니 verify = False 였음. 약간 warning 넘어가는 코드 느낌...?

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to host 'sg.sbiz.or.kr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

In [10]:
res.raise_for_status()

In [3]:
from selenium import webdriver

from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

#셀레늄에서 html문서가 생성될 때까지 대기하는 함수 불러오기
from selenium.webdriver.support.ui import WebDriverWait

#셀레늄에서 조건을 걸어줄 수 있는 함수 불러오기
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time
import pandas as pd

In [4]:
#크롬드라이버 경로 설정

import sys
sys.path.insert(0, '/usr/local/bin/chromedriver')

# 1. 부산광역시

## 1-1. 부산 업소현황

In [14]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/upso.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[3]/label").click() #부산선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_68249/232559683.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [5]:
#긁어오기시작 
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

In [7]:
busan_table= browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
busan_result = []
for a in busan_table :
    busan_result.append(a.text)

In [1]:
def list_chunk(lst, n):
    return [lst[i:i+n] for i in range(0, len(lst), n)]

In [9]:
busan_result = list_chunk(busan_result,4)
busan_result

[['부산광역시', '150,522', '150,225', '-0.2%'],
 ['┗ 중구', '7,034', '7,029', '-0.07%'],
 ['┗ 서구', '3,981', '3,995', '0.35%'],
 ['┗ 동구', '6,310', '6,252', '-0.92%'],
 ['┗ 영도구', '4,598', '4,516', '-1.78%'],
 ['┗ 부산진구', '17,929', '18,114', '1.03%'],
 ['┗ 동래구', '10,869', '10,801', '-0.63%'],
 ['┗ 남구', '9,582', '9,583', '0.01%'],
 ['┗ 북구', '8,330', '8,386', '0.67%'],
 ['┗ 해운대구', '17,437', '17,178', '-1.49%'],
 ['┗ 사하구', '12,096', '12,191', '0.79%'],
 ['┗ 금정구', '9,537', '9,631', '0.99%'],
 ['┗ 강서구', '7,148', '7,362', '2.99%'],
 ['┗ 연제구', '9,317', '8,040', '-13.71%'],
 ['┗ 수영구', '8,412', '8,281', '-1.56%'],
 ['┗ 사상구', '9,342', '9,497', '1.66%'],
 ['┗ 기장군', '7,404', '7,616', '2.86%']]

In [10]:
mycolumns = ['행정구역','2021상반기','2021하반기','증감률']

In [13]:
busan_df = pd.DataFrame(busan_result,columns=mycolumns)

In [14]:
busan_df

      행정구역  2021상반기  2021하반기      증감률
0    부산광역시  150,522  150,225    -0.2%
1     ┗ 중구    7,034    7,029   -0.07%
2     ┗ 서구    3,981    3,995    0.35%
3     ┗ 동구    6,310    6,252   -0.92%
4    ┗ 영도구    4,598    4,516   -1.78%
5   ┗ 부산진구   17,929   18,114    1.03%
6    ┗ 동래구   10,869   10,801   -0.63%
7     ┗ 남구    9,582    9,583    0.01%
8     ┗ 북구    8,330    8,386    0.67%
9   ┗ 해운대구   17,437   17,178   -1.49%
10   ┗ 사하구   12,096   12,191    0.79%
11   ┗ 금정구    9,537    9,631    0.99%
12   ┗ 강서구    7,148    7,362    2.99%
13   ┗ 연제구    9,317    8,040  -13.71%
14   ┗ 수영구    8,412    8,281   -1.56%
15   ┗ 사상구    9,342    9,497    1.66%
16   ┗ 기장군    7,404    7,616    2.86%

In [21]:
busan_df.to_csv("부산업소현황.csv",index=None)

## 1-2. 부산 지역현황

In [5]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/area.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[3]/label").click() #부산선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_77259/2006773526.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [11]:
busan_jiyuk_table= browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
busan_jiyuk_result = []
for a in busan_jiyuk_table :
    busan_jiyuk_result.append(a.text)

In [12]:
busan_jiyuk_result = list_chunk(busan_jiyuk_result,9)
busan_jiyuk_result

[['부산광역시',
  '1,447,571',
  '3,517,858',
  '12,014',
  '15,819',
  '4,842,727',
  '157,488',
  '9',
  '0.18'],
 ['┗ 중구', '23,262', '45,602', '404', '827', '3,681,718', '7,757', '3', '0.16'],
 ['┗ 서구',
  '53,054',
  '114,984',
  '396',
  '440',
  '4,041,771',
  '4,167',
  '13',
  '0.2'],
 ['┗ 동구', '43,242', '91,071', '437', '945', '4,023,252', '6,485', '7', '0.21'],
 ['┗ 영도구',
  '56,355',
  '128,515',
  '410',
  '466',
  '3,736,517',
  '4,469',
  '13',
  '0.2'],
 ['┗ 부산진구',
  '165,826',
  '381,125',
  '1,508',
  '2,062',
  '5,237,741',
  '20,049',
  '8',
  '0.18'],
 ['┗ 동래구',
  '106,989',
  '272,315',
  '922',
  '1,137',
  '5,485,981',
  '11,882',
  '9',
  '0.17'],
 ['┗ 남구',
  '114,553',
  '282,625',
  '797',
  '885',
  '4,981,080',
  '9,254',
  '12',
  '0.18'],
 ['┗ 북구',
  '119,888',
  '311,109',
  '870',
  '977',
  '4,627,616',
  '9,256',
  '13',
  '0.2'],
 ['┗ 해운대구',
  '165,759',
  '423,725',
  '1,402',
  '1,608',
  '4,717,655',
  '16,301',
  '10',
  '0.18'],
 ['┗ 사하구',
  '134,943',
  '336,204',
  '996',
  '1,272',
  '4,128,762',
  '13,913',
  '10',
  '0.16'],
 ['┗ 금정구',
  '102,466',
  '247,145',
  '789',
  '1,061',
  '4,977,063',
  '11,117',
  '9',
  '0.17'],
 ['┗ 강서구',
  '41,279',
  '101,701',
  '392',
  '535',
  '7,406,577',
  '6,199',
  '7',
  '0.15'],
 ['┗ 연제구',
  '85,138',
  '210,708',
  '879',
  '900',
  '5,375,389',
  '10,335',
  '8',
  '0.17'],
 ['┗ 수영구',
  '77,166',
  '180,067',
  '600',
  '759',
  '5,649,637',
  '7,883',
  '10',
  '0.17'],
 ['┗ 사상구',
  '96,493',
  '235,641',
  '683',
  '1,276',
  '4,529,176',
  '11,409',
  '8',
  '0.17'],
 ['┗ 기장군',
  '61,157',
  '155,320',
  '529',
  '669',
  '4,725,818',
  '7,012',
  '9',
  '0.17']]

In [15]:
jiyuk_columns = ['행정구역','총가구수','총인구수','주요시설수','집객시설수','아파트면적(1m2)당 기준시가(원)','업소수','업소당 가구수','업소당 시설물수']

In [16]:
busan_jiyuk_df = pd.DataFrame(busan_jiyuk_result,columns=jiyuk_columns)
busan_jiyuk_df

,행정구역,총가구수,총인구수,주요시설수,집객시설수,아파트면적(1m2)당 기준시가(원),업소수,업소당 가구수,업소당 시설물수
0,부산광역시,"1,447,571","3,517,858","12,014","15,819","4,842,727","157,488",9,0.18
1,┗ 중구,"23,262","45,602",404,827,"3,681,718","7,757",3,0.16
2,┗ 서구,"53,054","114,984",396,440,"4,041,771","4,167",13,0.2
3,┗ 동구,"43,242","91,071",437,945,"4,023,252","6,485",7,0.21
4,┗ 영도구,"56,355","128,515",410,466,"3,736,517","4,469",13,0.2
5,┗ 부산진구,"165,826","381,125","1,508","2,062","5,237,741","20,049",8,0.18
6,┗ 동래구,"106,989","272,315",922,"1,137","5,485,981","11,882",9,0.17
7,┗ 남구,"114,553","282,625",797,885,"4,981,080","9,254",12,0.18
8,┗ 북구,"119,888","311,109",870,977,"4,627,616","9,256",13,0.2
9,┗ 해운대구,"165,759","423,725","1,402","1,608","4,717,655","16,301",10,0.18
10,┗ 사하구,"134,943","336,204",996,"1,272","4,128,762","13,913",10,0.16
11,┗ 금정구,"102,466","247,145",789,"1,061","4,977,063","11,117",9,0.17
12,┗ 강서구,"41,279","101,701",392,535,"7,406,577","6,199",7,0.15
13,┗ 연제구,"85,138","210,708",879,900,"5,375,389","10,335",8,0.17
14,┗ 수영구,"77,166","180,067",600,759,"5,649,637","7,883",10,0.17
15,┗ 사상구,"96,493","235,641",683,"1,276","4,529,176","11,409",8,0.17
16,┗ 기장군,"61,157","155,320",529,669,"4,725,818","7,012",9,0.17

In [17]:
busan_jiyuk_df.to_csv("부산지역현황.csv",index=None)

# 2. 울산

## 2-1. 울산업소현황

In [15]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/upso.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[8]/label").click() #울산선택
time.sleep(1) 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[2]/div/ul/li[1]/label").click() #전체선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_32320/1635479218.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [16]:
ulsan_table= browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
ulsan_result = []
for a in ulsan_table :
    ulsan_result.append(a.text)

In [17]:
ulsan_result = list_chunk(ulsan_result,4)
ulsan_result

[['울산광역시', '52,564', '49,490', '-5.85%'],
 ['┗ 중구', '9,104', '8,694', '-4.5%'],
 ['┗ 남구', '19,393', '17,656', '-8.96%'],
 ['┗ 동구', '6,366', '5,406', '-15.08%'],
 ['┗ 북구', '7,637', '7,648', '0.14%'],
 ['┗ 울주군', '9,753', '9,630', '-1.26%']]

In [18]:
ulsan_df = pd.DataFrame(ulsan_result,columns=mycolumns)

In [19]:
ulsan_df

    행정구역 2021상반기 2021하반기      증감률
0  울산광역시  52,564  49,490   -5.85%
1   ┗ 중구   9,104   8,694    -4.5%
2   ┗ 남구  19,393  17,656   -8.96%
3   ┗ 동구   6,366   5,406  -15.08%
4   ┗ 북구   7,637   7,648    0.14%
5  ┗ 울주군   9,753   9,630   -1.26%

In [20]:
ulsan_df.to_csv("울산업소현황.csv",index=None)

## 2-2. 울산지역현황

In [18]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/area.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[8]/label").click() #울산선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_77259/3126344746.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [19]:
ulsan_jiyuk_table= browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
ulsan_jiyuk_result = []
for a in ulsan_jiyuk_table :
    ulsan_jiyuk_result.append(a.text)
    
ulsan_jiyuk_result = list_chunk(ulsan_jiyuk_result,9)
ulsan_jiyuk_result

ulsan_jiyuk_df = pd.DataFrame(ulsan_jiyuk_result,columns=jiyuk_columns)
print(ulsan_jiyuk_df)

ulsan_jiyuk_df.to_csv("울산지역현황.csv",index=None)

    행정구역     총가구수       총인구수  주요시설수  집객시설수 아파트면적(1m2)당 기준시가(원)     업소수  \
0  울산광역시  453,960  1,173,921  3,901  5,258           5,377,020  53,399
1   ┗ 중구   95,717    243,690    695  1,002           5,316,288  10,184
2   ┗ 남구  133,921    342,150  1,392  2,054           5,656,839  21,098
3   ┗ 동구   68,833    175,351    565    685           5,581,561   6,609
4   ┗ 북구   68,689    193,310    532    560           5,834,485   6,447
5  ┗ 울주군   86,799    219,420    717    957           4,393,234   9,061

  업소당 가구수 업소당 시설물수
0       9     0.17
1       9     0.17
2       6     0.16
3      10     0.19
4      11     0.17
5      10     0.18

# 3. 경북

## 3-1. 경북 업소 현황

In [22]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/upso.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)

itemlist = browser.find_element("xpath",'html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div')
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight)", itemlist)

time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[16]/label").click() #경북선택
time.sleep(1) 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[2]/div/ul/li[1]/label").click() #전체선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_32320/2373193097.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [23]:
kyungbuk_table= browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
kyungbuk_result = []
for a in kyungbuk_table :
    kyungbuk_result.append(a.text)

In [24]:
kyungbuk_result = list_chunk(kyungbuk_result, 4)
kyungbuk_df = pd.DataFrame(kyungbuk_result,columns=mycolumns)
kyungbuk_df

     행정구역  2021상반기  2021하반기      증감률
0    경상북도  164,296  154,469   -5.98%
1   ┗ 포항시   30,928   28,358   -8.31%
2   ┗ 경주시   20,496   19,508   -4.82%
3   ┗ 김천시    6,404    6,308    -1.5%
4   ┗ 안동시   11,890   10,911   -8.23%
5   ┗ 구미시   24,678   21,448  -13.09%
6   ┗ 영주시    7,275    6,949   -4.48%
7   ┗ 영천시    5,302    5,139   -3.07%
8   ┗ 상주시    6,156    5,515  -10.41%
9   ┗ 문경시    4,971    4,627   -6.92%
10  ┗ 경산시   13,829   13,559   -1.95%
11  ┗ 군위군    1,078    1,036    -3.9%
12  ┗ 의성군    2,595    2,508   -3.35%
13  ┗ 청송군    1,754    1,679   -4.28%
14  ┗ 영양군      790      745    -5.7%
15  ┗ 영덕군    3,341    3,190   -4.52%
16  ┗ 청도군    2,438    2,353   -3.49%
17  ┗ 고령군    1,559    1,518   -2.63%
18  ┗ 성주군    2,314    2,243   -3.07%
19  ┗ 칠곡군    6,549    6,366   -2.79%
20  ┗ 예천군    2,674    2,556   -4.41%
21  ┗ 봉화군    1,587    1,500   -5.48%
22  ┗ 울진군    3,736    3,611   -3.35%
23  ┗ 울릉군      688      669   -2.76%

In [25]:
kyungbuk_df.to_csv("경북업소현황.csv",index=None)

## 3-2. 경북지역현황

In [20]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/area.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)

itemlist = browser.find_element("xpath",'html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div')
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight)", itemlist)

time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[16]/label").click() #경북선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_77259/1451433267.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [21]:
kyungbuk_jiyuk_table= browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
kyungbuk_jiyuk_result = []
for a in kyungbuk_jiyuk_table :
    kyungbuk_jiyuk_result.append(a.text)
    
kyungbuk_jiyuk_result = list_chunk(kyungbuk_jiyuk_result,9)
kyungbuk_jiyuk_result

kyungbuk_jiyuk_df = pd.DataFrame(kyungbuk_jiyuk_result,columns=jiyuk_columns)
print(kyungbuk_jiyuk_df)

kyungbuk_jiyuk_df.to_csv("경북지역현황.csv",index=None)

     행정구역       총가구수       총인구수   주요시설수   집객시설수 아파트면적(1m2)당 기준시가(원)      업소수  \
0    경상북도  1,177,200  2,708,173  12,014  15,553           3,486,825  148,260
1   ┗ 포항시    212,021    519,836   1,660   2,715           3,553,949   29,118
2   ┗ 경주시    113,324    260,158   1,069   2,226           3,943,504   18,522
3   ┗ 김천시     62,236    142,987     519     658           3,065,128    6,083
4   ┗ 안동시     73,170    168,666     752   1,035           3,688,940   10,797
5   ┗ 구미시    168,803    421,757   1,426   2,135           3,603,259   23,036
6   ┗ 영주시     48,288    109,312     565     709           3,046,904    7,026
7   ┗ 영천시     47,234    100,418     543     492           2,899,923    4,806
8   ┗ 상주시     46,595    102,221     757     611           2,947,016    5,540
9   ┗ 문경시     34,603     75,315     500     530           3,072,085    4,227
10  ┗ 경산시    107,394    258,221     983     984           4,607,422   11,829
11  ┗ 군위군     12,294     24,119     147     133           2,296,278    1,011
12  ┗ 의성군     27,446     54,420     428     278           2,404,406    2,273
13  ┗ 청송군     13,437     26,488     200     192           2,437,739    1,521
14  ┗ 영양군      8,788     17,779     144      95           2,325,445      722
15  ┗ 영덕군     20,164     39,187     242     373           2,642,528    2,831
16  ┗ 청도군     21,609     43,667     333     309           2,814,215    2,050
17  ┗ 고령군     16,258     34,758     250     162           3,175,378    1,496
18  ┗ 성주군     21,535     44,863     225     239           2,979,840    2,126
19  ┗ 칠곡군     53,145    122,466     455     612           2,990,303    5,893
20  ┗ 예천군     21,986     45,880     288     233           3,083,513    2,114
21  ┗ 봉화군     16,415     33,687     195     186           2,346,952    1,428
22  ┗ 울진군     25,039     51,754     265     470           2,718,832    3,157
23  ┗ 울릉군      5,417     10,216      68     176           3,256,001      654

   업소당 가구수 업소당 시설물수
0        8     0.19
1        7     0.15
2        6     0.18
3       10     0.19
4        7     0.17
5        7     0.15
6        7     0.18
7       10     0.22
8        8     0.25
9        8     0.24
10       9     0.17
11      12     0.28
12      12     0.31
13       9     0.26
14      12     0.33
15       7     0.22
16      11     0.31
17      11     0.28
18      10     0.22
19       9     0.18
20      10     0.25
21      11     0.27
22       8     0.23
23       8     0.37

# 4.경남

## 4-1. 경남 업소현황

In [26]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/upso.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)

itemlist = browser.find_element("xpath",'html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div')
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight)", itemlist)

time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[17]/label").click() #경남선택
time.sleep(1) 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_32320/1282299841.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [27]:
kyungnam_table= browser.find_elements(By.CSS_SELECTOR,'#upsoTable > tr > td')
kyungnam_result = []
for a in kyungnam_table :
    kyungnam_result.append(a.text)

In [28]:
kyungnam_result = list_chunk(kyungnam_result, 4)
kyungnam_df = pd.DataFrame(kyungnam_result,columns=mycolumns)
kyungnam_df

     행정구역  2021상반기  2021하반기      증감률
0    경상남도  182,749  175,214   -4.12%
1   ┗ 창원시   58,809   57,003   -3.07%
2   ┗ 진주시   18,615   18,518   -0.52%
3   ┗ 통영시    8,864    8,479   -4.34%
4   ┗ 사천시    6,497    6,346   -2.32%
5   ┗ 김해시   26,124   22,926  -12.24%
6   ┗ 밀양시    6,477    6,108    -5.7%
7   ┗ 거제시   11,996   11,946   -0.42%
8   ┗ 양산시   16,019   14,647   -8.56%
9   ┗ 의령군    1,325    1,284   -3.09%
10  ┗ 함안군    3,134    3,044   -2.87%
11  ┗ 창녕군    3,790    3,675   -3.03%
12  ┗ 고성군    3,292    3,191   -3.07%
13  ┗ 남해군    2,954    2,933   -0.71%
14  ┗ 하동군    3,032    2,947    -2.8%
15  ┗ 산청군    2,389    2,345   -1.84%
16  ┗ 함양군    2,427    2,333   -3.87%
17  ┗ 거창군    3,527    3,424   -2.92%
18  ┗ 합천군    2,469    2,374   -3.85%

In [29]:
kyungnam_df.to_csv("경남업소현황.CSV",index=None)

## 4-2. 경남 지역 현황

In [22]:
#크롬드라이버 경로 설정
path = '/usr/local/bin/chromedriver'
browser = webdriver.Chrome(path)


browser.get('https://sg.sbiz.or.kr/godo/stat/area.sg')
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[1]/ul/li[1]/div/div[2]/a").click() #지역선택 누르기
time.sleep(3)

itemlist = browser.find_element("xpath",'html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div')
browser.execute_script("arguments[0].scrollBy(0, document.body.scrollHeight)", itemlist)
time.sleep(1)
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[1]/div/ul/li[1]/div/ul/li[17]/label").click() #경남선택
time.sleep(1) 
browser.find_element("xpath","/html/body/div[2]/div/div[2]/div/div[2]/a[2]/span").click() #확인선택
time.sleep(1)
browser.find_element("xpath","/html/body/div[1]/div[2]/div[1]/div[2]/div/div/div[1]/div/div[2]/a").click() #현황보기

/var/folders/hn/cd349ymj15z52npp7jj0gfnc0000gn/T/ipykernel_77259/1640093945.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(path)

In [23]:
kyungnam_jiyuk_table= browser.find_elements(By.CSS_SELECTOR,'#tableBody > tr > td')
kyungnam_jiyuk_result = []
for a in kyungnam_jiyuk_table :
    kyungnam_jiyuk_result.append(a.text)
    
kyungnam_jiyuk_result = list_chunk(kyungnam_jiyuk_result,9)
kyungnam_jiyuk_result

kyungnam_jiyuk_df = pd.DataFrame(kyungnam_jiyuk_result,columns=jiyuk_columns)
print(kyungnam_jiyuk_df)

kyungnam_jiyuk_df.to_csv("경남지역현황.csv",index=None)

     행정구역       총가구수       총인구수   주요시설수   집객시설수 아파트면적(1m2)당 기준시가(원)      업소수  \
0    경상남도  1,375,996  3,368,020  13,316  18,873           4,694,424  174,259
1   ┗ 창원시    417,479  1,067,462   3,912   5,991           5,593,272   60,235
2   ┗ 진주시    140,303    347,856   1,316   1,858           4,360,199   18,749
3   ┗ 통영시     59,124    138,693     570     948           3,991,957    7,983
4   ┗ 사천시     50,677    115,169     508     714           3,215,522    6,389
5   ┗ 김해시    198,935    528,762   1,519   2,398           4,565,688   24,244
6   ┗ 밀양시     49,523    108,030     534     658           3,229,377    5,739
7   ┗ 거제시    102,540    257,287     797   1,456           5,515,436   11,459
8   ┗ 양산시    120,185    306,405     940   1,229           4,470,345   13,427
9   ┗ 의령군     14,384     28,246     206     159           3,130,637    1,297
10  ┗ 함안군     31,043     68,932     288     320           4,170,966    2,927
11  ┗ 창녕군     30,545     63,902     396     399           3,019,037    3,587
12  ┗ 고성군     25,860     54,816     359     380           3,141,158    3,134
13  ┗ 남해군     22,132     45,471     334     578           2,992,268    2,634
14  ┗ 하동군     23,471     49,647     306     415           2,337,323    2,797
15  ┗ 산청군     18,207     36,228     243     350           2,994,276    1,973
16  ┗ 함양군     19,417     39,958     270     306           3,288,482    2,222
17  ┗ 거창군     27,987     63,239     434     372           2,802,977    3,177
18  ┗ 합천군     24,184     47,915     384     342           2,881,185    2,286

   업소당 가구수 업소당 시설물수
0        8     0.18
1        7     0.16
2        7     0.17
3        7     0.19
4        8     0.19
5        8     0.16
6        9     0.21
7        9      0.2
8        9     0.16
9       11     0.28
10      11     0.21
11       9     0.22
12       8     0.24
13       8     0.35
14       8     0.26
15       9      0.3
16       9     0.26
17       9     0.25
18      11     0.32

# 과제

### 1. 위의 코드 이해하기
### 2. 위의 코드를 활용하여 각자 맡은 지역의 상권 정보를 긁어 csv 파일로 만들기

https://sg.sbiz.or.kr/godo/stat/upso.sg
### 3. csv 파일은 구글 드라이브에 업로드할 것. jupyter notebook으로 크롤링 진행 후 ipynb 파일을 각자 DSL 깃에서 fork하여 pull request 하는 형식으로 제출